### ISSUE TITLE
[FEATURE] NE isolation

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/agent#119]
- [x] Use docker-compose project as main prefix for docker service 
- [x] Add configurability to external network ports.
- [x] Network naming should be controlled and prefixed by docker-compose.
- [ ] #138

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to run two NE in the same device

**Describe the solution you'd like**
Provide engine isolation by improving the configurability of the engine

**Comment by ignacio-penas** [comment]
- [ ] Use docker-compose project as main prefix for docker service 
- [ ] Add configurability to external network ports.
- [ ] Network naming should be controlled and prefixed by docker-compose.
- [ ] New app deployment should follow this premises too

**Comment by konstan** [comment]
@ignacio-penas Please create separate issues per the tasks that are still not done in the list above.
