### ISSUE TITLE
[BUG] Lack of logging report when the agent cannot find the .status file

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/agent#135]
The status file should first by created and initialized by nuvlaedge/system-manager. When an error occurs, and this file is not reachable by the agent there is no way of tracking the error. 

A log prompt should be added in this while loop: https://github.com/nuvlaedge/agent/blob/d580ec2b792e287dfc145e733b8a370789c18d35/code/agent/agent.py#L69-L74

**Comment by schaubl** [comment]
Fixed in nuvlaedge/agent@6b2c7028fb6566b0b2536d662d1651673d10995b
And then unfixed by mistake during a merge in nuvlaedge/agent@2618a21dfa7657a9d1b3eabcf2b65afc548f9e8f
Finally fixed again in nuvlaedge/nuvlaedge@0ed3f5c61eea1024688caf4f6394b52238e0f4e9
