### ISSUE TITLE
[BUG] CI: switch GHA workflow runner to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/agent#145]
**Describe the bug**

The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

**Comment by schaubl** [comment]
Done with `ubuntu-latest`. Testing ...
