### ISSUE TITLE
[BUG] logs from Kubernetes driver are not visible in agent logs

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/agent#146]
**Describe the bug**

Logs from the Kubernetes driver are not visible in agent logs. This might also be the case for the Docker driver.

**Expected behavior**
Logs from Kubernetes (and Docker) driver(s) are visible in agent logs.

**Comment by schaubl** [comment]
Fixed in nuvlaedge/nuvlaedge@31627c2fe55c4836d27ea0dd73dca96c0f67df7b
