### ISSUE TITLE
validate NE on k8s works in pull mode

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/agent#168]
- [x] k3s
- [x] k0s
- [x] k8s

**Comment by giovannibianco** [comment]
Verify that the NuvlaEdge works in pull mode...
[] Deploy NulvaEdge via k8s on a VM behind a NAT.
* Make sure that NUVLA_JOB_PULL is set up.
* Or set NUVLA_JOB_PULL.
* Make a deployment to the k8s NuvlaEdge.

**Comment by giovannibianco** [comment]
At the moment, there is the problem with the credential not valid for the IP address presented.
Checking how the SANs are added to the certificate ... and when.
If the VPN is not up at the time that the certificate is written then the VPN IP address is not added
and we get the error as seen on the UI.

**Comment by giovannibianco** [comment]
More detailed:
We use k3s for now to avoid "problems"
- [] Deploy the nuvlaedge to the k3s VM
- []Make sure the credentials are approved/created. Check with `kubectl get csr nuvlaedge-csr -o jsonpath="{.status.certificate}" | base64 -d`
-[] Now block the incoming traffic to the VPN interface...
`VPN_IP=$(ip a | grep -i vpn | grep -i inet | awk -F " " '{print $2}' | tr "/" " " | awk -F " " '{print $1}')`
`iptables -I INPUT 5 -d $VPN_IP --protocol udp -j REJECT`
-[] Make the app deployment...

Shows same behaviour as before... failure in first try (x.509...) and success on the second.

**Comment by giovannibianco** [comment]
Exercise...
- [ ] Unblock the VPN
- [ ] Restart the vpn-client pod
- [ ] Check if the Nginx page can be accessed.
